// Generated-image manifest — slug → cached public path.
//
// AUTO-GENERATED by scripts/generate-feed-images.mjs. Do not edit by hand.
// Until the generator runs, this is empty and the feed falls back to Unsplash.
//
// This file is intentionally data-only and safe to import on the edge.

export const GENERATED_IMAGES: Record<string, string> = {
  "hexapod-walking-robot": "/innovations/hexapod-walking-robot.png",
  "soil-moisture-mesh-network": "/innovations/soil-moisture-mesh-network.png",
  "e-ink-smartwatch": "/innovations/e-ink-smartwatch.png",
  "65w-gan-charger-board": "/innovations/65w-gan-charger-board.png",
  "pocket-synth-sequencer": "/innovations/pocket-synth-sequencer.png",
  "line-following-micro-rover": "/innovations/line-following-micro-rover.png",
  "air-quality-room-sensor": "/innovations/air-quality-room-sensor.png",
  "gesture-control-glove": "/innovations/gesture-control-glove.png",
  "solar-mppt-controller": "/innovations/solar-mppt-controller.png",
  "lo-fi-guitar-pedal": "/innovations/lo-fi-guitar-pedal.png",
  "robotic-arm-with-haptics": "/innovations/robotic-arm-with-haptics.png",
  "smart-plant-watering-hub": "/innovations/smart-plant-watering-hub.png",
  "heart-rate-fitness-band": "/innovations/heart-rate-fitness-band.png",
  "bench-power-supply-0-30v": "/innovations/bench-power-supply-0-30v.png",
  "eurorack-noise-module": "/innovations/eurorack-noise-module.png",
  "self-balancing-two-wheeler": "/innovations/self-balancing-two-wheeler.png",
  "door-window-contact-sensor": "/innovations/door-window-contact-sensor.png",
  "ar-caption-glasses": "/innovations/ar-caption-glasses.png",
  "usb-c-power-meter": "/innovations/usb-c-power-meter.png",
  "portable-contact-mic-mixer": "/innovations/portable-contact-mic-mixer.png",
  "swarm-beacon-drone": "/innovations/swarm-beacon-drone.png",
  "lora-weather-station": "/innovations/lora-weather-station.png",
  "posture-tracking-pendant": "/innovations/posture-tracking-pendant.jpg",
  "18650-battery-balancer": "/innovations/18650-battery-balancer.jpg",
  "tube-preamp-clone": "/innovations/tube-preamp-clone.jpg",
  "quadruped-pet-companion": "/innovations/quadruped-pet-companion.jpg",
  "desk-occupancy-tracker": "/innovations/desk-occupancy-tracker.jpg",
  "sleep-stage-ring": "/innovations/sleep-stage-ring.jpg",
  "wireless-qi-charge-pad": "/innovations/wireless-qi-charge-pad.jpg",
  "granular-sampler-box": "/innovations/granular-sampler-box.jpg",
  "pick-and-place-head": "/innovations/pick-and-place-head.jpg",
  "greenhouse-climate-node": "/innovations/greenhouse-climate-node.jpg",
  "haptic-navigation-cuff": "/innovations/haptic-navigation-cuff.jpg",
  "supercapacitor-jump-pack": "/innovations/supercapacitor-jump-pack.jpg",
  "modular-drum-machine": "/innovations/modular-drum-machine.jpg",
  "cable-driven-gripper": "/innovations/cable-driven-gripper.jpg",
};
