// IDEEZA PCB Software — Hugeicons map.
// Maps the editor's icon keys to @hugeicons/core-free-icons icon objects.
// Adopts the IDEEZA design-system icon set (Hugeicons) for editor chrome.
import {
  Activity01Icon,
  AlignBottomIcon,
  AlignHorizontalCenterIcon,
  AlignHorizontalDistributeCenterIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignSelectionIcon,
  AlignTopIcon,
  AlignVerticalCenterIcon,
  AlignVerticalDistributeCenterIcon,
  ArrowDataTransferHorizontalIcon,
  ArrowDataTransferVerticalIcon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  Book02Icon,
  BubbleChatIcon,
  ContactIcon,
  DashboardSpeed01Icon,
  Cancel01Icon,
  CheckmarkCircle01Icon,
  CheckmarkSquare01Icon,
  CheckmarkSquare02Icon,
  ChipIcon,
  CircleIcon,
  ClipboardIcon,
  CodeIcon,
  ComputerIcon,
  ConnectIcon,
  Copy01Icon,
  Copy02Icon,
  CpuIcon,
  CubeIcon,
  Cursor01Icon,
  DashboardSquare01Icon,
  DashboardSquare02Icon,
  Delete02Icon,
  EyeIcon,
  File01Icon,
  FileExportIcon,
  FileImportIcon,
  Flag01Icon,
  Flag02Icon,
  FlashIcon,
  FlipHorizontalIcon,
  FlipVerticalIcon,
  FloppyDiskIcon,
  FolderOpenIcon,
  FullScreenIcon,
  GridIcon,
  GroupItemsIcon,
  Image01Icon,
  InformationCircleIcon,
  KeyboardIcon,
  Layers01Icon,
  Magnet01Icon,
  Moon02Icon,
  Move01Icon,
  OnlineLearning01Icon,
  PaintBoardIcon,
  Png01Icon,
  RepeatIcon,
  Route02Icon,
  Sun01Icon,
  UserGroupIcon,
  Video01Icon,
  WindowsNewIcon,
  LeftToRightListBulletIcon,
  LineIcon,
  Login03Icon,
  Menu01Icon,
  PathIcon,
  Pdf01Icon,
  Pen01Icon,
  PencilEdit01Icon,
  PolygonIcon,
  RadialIcon,
  RecordIcon,
  RefreshIcon,
  RotateClockwiseIcon,
  RulerIcon,
  Scissor01Icon,
  Search02Icon,
  SearchAddIcon,
  Settings02Icon,
  SmartPhone01Icon,
  SquareArrowExpand01Icon,
  SquareIcon,
  Table01Icon,
  Tag01Icon,
  TextFontIcon,
  TextIcon,
  Tick02Icon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
} from "@hugeicons/core-free-icons";

export const HICON: Record<string, typeof Activity01Icon> = {
  pcb: CpuIcon,
  code: CodeIcon,
  cube: CubeIcon,
  preview: EyeIcon,
  brief: File01Icon,
  page: File01Icon,
  board: DashboardSquare01Icon,
  sch: Activity01Icon,
  chip: ChipIcon,
  logs: Menu01Icon,
  device: SmartPhone01Icon,
  drc: CheckmarkCircle01Icon,
  result: CheckmarkSquare01Icon,
  sys: ComputerIcon,
  draw: PencilEdit01Icon,
  key: KeyboardIcon,
  prop: Settings02Icon,
  save: FloppyDiskIcon,
  font: TextFontIcon,
  foot: DashboardSquare02Icon,
  panel: DashboardSquare01Icon,
  symbol: Activity01Icon,
  copy: Copy01Icon,
  paste: ClipboardIcon,
  cut: Scissor01Icon,
  del: Delete02Icon,
  dup: Copy02Icon,
  rot: RotateClockwiseIcon,
  find: SearchAddIcon,
  findSim: Search02Icon,
  undo: ArrowTurnBackwardIcon,
  redo: ArrowTurnForwardIcon,
  check: Tick02Icon,
  array: GridIcon,
  zoomin: ZoomInAreaIcon,
  zoomout: ZoomOutAreaIcon,
  fit: FullScreenIcon,
  grid: GridIcon,
  ruler: RulerIcon,
  wire: ConnectIcon,
  power: FlashIcon,
  layer: Layers01Icon,
  measure: RulerIcon,
  pdf: Pdf01Icon,
  gerber: FileExportIcon,
  bom: LeftToRightListBulletIcon,
  imp: FileImportIcon,
  rules: CheckmarkSquare02Icon,
  convert: ArrowDataTransferHorizontalIcon,
  doc: Book02Icon,
  rectIn: SquareIcon,
  rectOut: SquareIcon,
  polyIn: PolygonIcon,
  polyOut: PolygonIcon,
  lineT: LineIcon,
  toggleSel: Cursor01Icon,
  fitsel: SquareArrowExpand01Icon,
  fitarea: SquareArrowExpand01Icon,
  fullscreen: FullScreenIcon,
  pWire: ConnectIcon,
  pBus: ConnectIcon,
  pNetLabel: Tag01Icon,
  pShortFlag: Flag02Icon,
  pNetFlag: Flag01Icon,
  pPort: Login03Icon,
  pNoConnect: Cancel01Icon,
  pTestPoint: RecordIcon,
  pChip: ChipIcon,
  pPolyline: PathIcon,
  pArc: RadialIcon,
  pBezier: Pen01Icon,
  pCircle: CircleIcon,
  pEllipse: CircleIcon,
  pRect: SquareIcon,
  pText: TextIcon,
  pImage: Image01Icon,
  pTable: Table01Icon,
  dConvert: ArrowDataTransferHorizontalIcon,
  dLayout: DashboardSquare01Icon,
  dImport: FileImportIcon,
  dRule: RulerIcon,
  dCheck: CheckmarkCircle01Icon,
  dAnnotate: TextIcon,
  dCross: ConnectIcon,
  dTransfer: ArrowDataTransferVerticalIcon,
  dReset: RefreshIcon,
  // Menu-bar additions — every menu item carries a glyph.
  move: Move01Icon,
  group: GroupItemsIcon,
  align: AlignSelectionIcon,
  alignLeft: AlignLeftIcon,
  alignRight: AlignRightIcon,
  alignTop: AlignTopIcon,
  alignBottom: AlignBottomIcon,
  alignHCenter: AlignHorizontalCenterIcon,
  alignVCenter: AlignVerticalCenterIcon,
  distribute: AlignHorizontalDistributeCenterIcon,
  distributeV: AlignVerticalDistributeCenterIcon,
  flip: FlipHorizontalIcon,
  flipV: FlipVerticalIcon,
  folder: FolderOpenIcon,
  snap: Magnet01Icon,
  repeat: RepeatIcon,
  window: WindowsNewIcon,
  png: Png01Icon,
  route: Route02Icon,
  exp: FileExportIcon,
  appearance: PaintBoardIcon,
  community: UserGroupIcon,
  tutorial: OnlineLearning01Icon,
  contact: ContactIcon,
  chat: BubbleChatIcon,
  about: InformationCircleIcon,
  video: Video01Icon,
  diagnostic: DashboardSpeed01Icon,
  sun: Sun01Icon,
  moon: Moon02Icon,
};
