// KiCad board export — turns the editor's canvas document into a real
// `.kicad_pcb` file (KiCad 8/9 S-expression format). This is the bridge that
// makes the PCB step a real product: the same file opens in KiCad and feeds
// `kicad-cli` server-side for DRC / Gerber / drill / BOM outputs.
//
// Unit model: canvas coordinates are treated as 0.25 mm per unit (the default
// 720×480 board ⇒ 180×120 mm), matching the 3D views' scale assumption
// (100 canvas units = 1 scene unit ≈ 25 mm).

import type { CanvasObject, PcbState } from "./types";

export const CANVAS_TO_MM = 0.25;

// Object kinds that become footprints on the board.
const FOOTPRINT_KINDS = new Set([
  "component",
  "resistor",
  "capacitor",
  "inductor",
  "diode",
  "ic",
  "connector",
]);

const KIND_PREFIX: Record<string, string> = {
  resistor: "R",
  capacitor: "C",
  inductor: "L",
  diode: "D",
  connector: "J",
  ic: "U",
  component: "U",
};

const mm = (canvasUnits: number) => +(canvasUnits * CANVAS_TO_MM).toFixed(4);
const milToMm = (mil: number) => +(mil * 0.0254).toFixed(4);
const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

// The slices of PcbState the exporter reads — callers may pass the whole
// state or a persisted document.
export type KicadExportDoc = Pick<PcbState, "objects" | "pcbBoard" | "threeD">;

export function buildKicadPcb(doc: KicadExportDoc, projectName = "ideeza-board"): string {
  const objects = doc.objects ?? [];
  const boardW = mm(doc.pcbBoard?.width || 720);
  const boardH = mm(doc.pcbBoard?.height || 480);
  const thicknessMm = (() => {
    const m = /([0-9.]+)/.exec(doc.threeD?.boardThickness ?? "");
    const v = m ? Number(m[1]) : NaN;
    return isFinite(v) && v > 0 ? v : 1.6;
  })();

  // Net table: net 0 is KiCad's "no net"; every named net gets an index.
  const netNames: string[] = [];
  for (const o of objects) {
    if (o.net && !netNames.includes(o.net)) netNames.push(o.net);
  }
  const netIndex = (name?: string) =>
    name ? netNames.indexOf(name) + 1 : 0;

  const lines: string[] = [];
  lines.push(`(kicad_pcb`);
  lines.push(`  (version 20240108)`);
  lines.push(`  (generator "ideeza-creator")`);
  lines.push(`  (generator_version "1.0")`);
  lines.push(`  (general (thickness ${thicknessMm}) (legacy_teardrops no))`);
  lines.push(`  (paper "A4")`);
  lines.push(`  (title_block (title "${esc(projectName)}") (comment 1 "Generated by IDEEZA Creator"))`);
  lines.push(`  (layers`);
  lines.push(`    (0 "F.Cu" signal)`);
  lines.push(`    (31 "B.Cu" signal)`);
  lines.push(`    (36 "B.SilkS" user "B.Silkscreen")`);
  lines.push(`    (37 "F.SilkS" user "F.Silkscreen")`);
  lines.push(`    (38 "B.Mask" user)`);
  lines.push(`    (39 "F.Mask" user)`);
  lines.push(`    (40 "Dwgs.User" user "User.Drawings")`);
  lines.push(`    (44 "Edge.Cuts" user)`);
  lines.push(`    (46 "B.CrtYd" user "B.Courtyard")`);
  lines.push(`    (47 "F.CrtYd" user "F.Courtyard")`);
  lines.push(`    (48 "B.Fab" user)`);
  lines.push(`    (49 "F.Fab" user)`);
  lines.push(`  )`);
  lines.push(`  (setup (pad_to_mask_clearance 0))`);
  lines.push(`  (net 0 "")`);
  netNames.forEach((n, i) => lines.push(`  (net ${i + 1} "${esc(n)}")`));

  // Board outline on Edge.Cuts.
  lines.push(
    `  (gr_rect (start 0 0) (end ${boardW} ${boardH}) ` +
      `(stroke (width 0.1) (type solid)) (fill none) (layer "Edge.Cuts"))`,
  );

  // Footprints — one simple courtyard/silk body + reference designator per
  // physical component. (Pad geometry comes later with a real footprint
  // library; a padless footprint is valid and keeps placement + BOM data.)
  const kindCounters: Record<string, number> = {};
  for (const o of objects) {
    if (!FOOTPRINT_KINDS.has(o.kind)) continue;
    const prefix = KIND_PREFIX[o.kind] ?? "U";
    kindCounters[prefix] = (kindCounters[prefix] ?? 0) + 1;
    const ref = `${prefix}${kindCounters[prefix]}`;
    const w = mm(o.width ?? 40);
    const h = mm(o.height ?? o.width ?? 40);
    const cx = mm(o.x) + w / 2;
    const cy = mm(o.y) + h / 2;
    const rot = o.rotation ?? 0;
    const layer = o.side === "bottom" ? "B.Cu" : "F.Cu";
    const silk = o.side === "bottom" ? "B.SilkS" : "F.SilkS";
    const crtyd = o.side === "bottom" ? "B.CrtYd" : "F.CrtYd";
    lines.push(`  (footprint "IDEEZA:${esc(o.footprint || o.kind)}"`);
    lines.push(`    (layer "${layer}")`);
    lines.push(`    (at ${+cx.toFixed(4)} ${+cy.toFixed(4)} ${rot})`);
    lines.push(
      `    (property "Reference" "${ref}" (at 0 ${-(h / 2 + 1).toFixed(2)} ${rot}) (layer "${silk}") ` +
        `(effects (font (size 1 1) (thickness 0.15))))`,
    );
    lines.push(
      `    (property "Value" "${esc(o.comment || o.kind)}" (at 0 ${(h / 2 + 1).toFixed(2)} ${rot}) (layer "F.Fab") ` +
        `(effects (font (size 1 1) (thickness 0.15))))`,
    );
    const hw = +(w / 2).toFixed(4);
    const hh = +(h / 2).toFixed(4);
    lines.push(
      `    (fp_rect (start ${-hw} ${-hh}) (end ${hw} ${hh}) ` +
        `(stroke (width 0.12) (type solid)) (fill none) (layer "${silk}"))`,
    );
    lines.push(
      `    (fp_rect (start ${-(hw + 0.25).toFixed(4)} ${-(hh + 0.25).toFixed(4)}) (end ${(hw + 0.25).toFixed(4)} ${(hh + 0.25).toFixed(4)}) ` +
        `(stroke (width 0.05) (type solid)) (fill none) (layer "${crtyd}"))`,
    );
    lines.push(`  )`);
  }

  // Standalone pads become one-pad footprints (KiCad pads live in footprints).
  let padN = 0;
  for (const o of objects) {
    if (o.kind !== "pad") continue;
    padN += 1;
    const size = milToMm(o.width ?? 60) || 1.5;
    const drill = o.drill ? milToMm(o.drill) : 0;
    const shape = o.padShape === "rect" ? "rect" : o.padShape === "oval" ? "oval" : "circle";
    const tht = (o.padType ?? (drill > 0 ? "tht" : "smd")) === "tht";
    lines.push(`  (footprint "IDEEZA:PAD"`);
    lines.push(`    (layer "F.Cu")`);
    lines.push(`    (at ${mm(o.x)} ${mm(o.y)})`);
    lines.push(
      `    (property "Reference" "P${padN}" (at 0 -1.5) (layer "F.SilkS") ` +
        `(effects (font (size 0.8 0.8) (thickness 0.12))))`,
    );
    lines.push(
      `    (pad "1" ${tht ? "thru_hole" : "smd"} ${shape} (at 0 0) (size ${size} ${size}) ` +
        `${tht && drill > 0 ? `(drill ${drill}) ` : ""}` +
        `(layers ${tht ? '"*.Cu" "*.Mask"' : '"F.Cu" "F.Mask" "F.Paste"'}) (net ${netIndex(o.net)} "${esc(o.net ?? "")}"))`,
    );
    lines.push(`  )`);
  }

  // Tracks → copper segments.
  for (const o of objects) {
    if (o.kind !== "track" || o.endX === undefined || o.endY === undefined) continue;
    const width = milToMm(o.width ?? 10) || 0.25;
    const layer = o.layer === "bottom" || o.side === "bottom" ? "B.Cu" : "F.Cu";
    lines.push(
      `  (segment (start ${mm(o.x)} ${mm(o.y)}) (end ${mm(o.endX)} ${mm(o.endY)}) ` +
        `(width ${width}) (layer "${layer}") (net ${netIndex(o.net)}))`,
    );
  }

  // Vias.
  for (const o of objects) {
    if (o.kind !== "via" && o.kind !== "sutureVias") continue;
    const size = milToMm(o.width ?? 32) || 0.8;
    const drill = milToMm(o.drill ?? 16) || 0.4;
    lines.push(
      `  (via (at ${mm(o.x)} ${mm(o.y)}) (size ${size}) (drill ${drill}) ` +
        `(layers "F.Cu" "B.Cu") (net ${netIndex(o.net)}))`,
    );
  }

  // Free text on silkscreen.
  for (const o of objects) {
    if (o.kind !== "text" || !o.text) continue;
    lines.push(
      `  (gr_text "${esc(o.text)}" (at ${mm(o.x)} ${mm(o.y)} ${o.rotation ?? 0}) (layer "F.SilkS") ` +
        `(effects (font (size 1.2 1.2) (thickness 0.2))))`,
    );
  }

  lines.push(`)`);
  return lines.join("\n") + "\n";
}

// ── Client helpers (browser only) ───────────────────────────────────────

export function downloadTextFile(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 4000);
}

// Export the current document as a .kicad_pcb download.
export function exportKicadPcb(doc: KicadExportDoc, toast?: (m: string) => void) {
  const text = buildKicadPcb(doc);
  downloadTextFile("ideeza-board.kicad_pcb", text);
  toast?.("Exported ideeza-board.kicad_pcb — opens in KiCad 8+");
}

// Ask the server to run kicad-cli (Gerber). Downloads a zip when the server
// has KiCad; explains what to install when it doesn't.
export async function exportGerberViaKicad(
  doc: KicadExportDoc,
  toast?: (m: string) => void,
) {
  toast?.("Generating Gerbers…");
  try {
    const res = await fetch("/api/kicad", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ job: "gerber", board: buildKicadPcb(doc) }),
    });
    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "ideeza-gerbers.zip";
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.setTimeout(() => URL.revokeObjectURL(url), 4000);
      toast?.("Gerbers exported");
      return;
    }
    const body = (await res.json().catch(() => null)) as { error?: string } | null;
    toast?.(body?.error ?? "Gerber export failed");
  } catch {
    toast?.("Gerber export failed — server unreachable");
  }
}
