// A catalogue part's land pattern, resolved from its package name.
//
// The converter's `FOOTPRINT` map is keyed by symbol *kind*, so every IC in the
// catalogue gets the same SOIC-8 whatever it really is — an ESP32-C3-MINI-1 in
// SMD-53 and an STM32 in TSSOP-20 come out identical. A package name, unlike a
// kind, does determine the geometry: `0402`, `SOT-23-6` and `QFN-56` are
// standardised, and that is what this resolves.
//
// The pads themselves are generated by the **New Package wizard's own
// generator** (`lib/package/wizard.ts` `padsFor`), so a catalogue part and a
// hand-authored one are described by one piece of code rather than two that can
// drift. What comes out is nominal reference geometry — the datasheet's own
// land recommendation — not an IPC-7351 toe/heel/side calculation.
//
// A package this cannot parse resolves to `null` on purpose. An invented land
// pattern is worse than an honest gap, and every surface that shows one is
// expected to say so.

import { FAMILIES, padsFor } from "@/lib/package/wizard";
import type { FpPad } from "@/lib/package/types";

export type LandPattern = {
  /** The package the geometry was derived from, e.g. "SOT-23-6". */
  pkg: string;
  /** Which wizard family produced it — shown so the derivation is inspectable. */
  family: string;
  /** How many electrical pads it has. */
  count: number;
  pads: FpPad[];
};

const family = (id: string) => FAMILIES.find((f) => f.id === id);

/** Chip (two-terminal) packages, by their imperial code. Gap is the inner edge
 *  separation and pad size the datasheet's nominal land, both mm. */
const CHIP: Record<string, { gap: number; padW: number; padH: number }> = {
  "0201": { gap: 0.3, padW: 0.3, padH: 0.3 },
  "0402": { gap: 0.5, padW: 0.6, padH: 0.6 },
  "0603": { gap: 0.7, padW: 0.8, padH: 0.9 },
  "0805": { gap: 0.9, padW: 1.0, padH: 1.3 },
  "1206": { gap: 1.6, padW: 1.2, padH: 1.6 },
  "1210": { gap: 1.6, padW: 1.2, padH: 2.7 },
  "1806": { gap: 2.2, padW: 1.4, padH: 1.8 },
  "2010": { gap: 3.0, padW: 1.4, padH: 2.7 },
  "2512": { gap: 4.0, padW: 1.6, padH: 3.4 },
};

/** Two-terminal packages named rather than coded — diodes, mostly. */
const TWO_PAD: Record<string, { gap: number; padW: number; padH: number }> = {
  "SOD-123": { gap: 1.6, padW: 1.0, padH: 1.2 },
  "SOD-323": { gap: 1.2, padW: 0.8, padH: 0.9 },
  SMA: { gap: 2.6, padW: 1.6, padH: 1.8 },
  SMB: { gap: 3.2, padW: 2.2, padH: 2.2 },
  SMC: { gap: 4.0, padW: 2.6, padH: 3.0 },
};

/** Dual-row packages: pitch and row spacing are the package's, the count comes
 *  from the name (`SOIC-8` → 8) or from a default when the name omits it. */
const DUAL: Record<string, { pitch: number; rowSpacing: number; padW: number; padH: number; count: number; tht?: boolean }> = {
  SOIC: { pitch: 1.27, rowSpacing: 5.3, padW: 0.6, padH: 1.5, count: 8 },
  SOP: { pitch: 1.27, rowSpacing: 5.3, padW: 0.6, padH: 1.5, count: 8 },
  SSOP: { pitch: 0.65, rowSpacing: 5.5, padW: 0.4, padH: 1.4, count: 16 },
  TSSOP: { pitch: 0.65, rowSpacing: 5.9, padW: 0.4, padH: 1.45, count: 20 },
  MSOP: { pitch: 0.65, rowSpacing: 4.4, padW: 0.4, padH: 1.1, count: 8 },
  "SOT-23": { pitch: 0.95, rowSpacing: 2.3, padW: 0.6, padH: 1.0, count: 3 },
  SOT: { pitch: 0.95, rowSpacing: 2.3, padW: 0.6, padH: 1.0, count: 3 },
  TSOT: { pitch: 0.65, rowSpacing: 2.3, padW: 0.4, padH: 0.9, count: 6 },
  DIP: { pitch: 2.54, rowSpacing: 7.62, padW: 1.6, padH: 1.6, count: 8, tht: true },
  SOIC_W: { pitch: 1.27, rowSpacing: 9.0, padW: 0.6, padH: 1.8, count: 16 },
};

/** Quad packages — pins on all four sides. `span` is centre-to-row (pads land
 *  at ±span), and acts as a floor: the real value is derived from the count. */
const QUAD: Record<string, { pitch: number; span: number; padW: number; padH: number }> = {
  QFN: { pitch: 0.5, span: 2.0, padW: 0.28, padH: 0.75 },
  QFP: { pitch: 0.8, span: 3.0, padW: 0.4, padH: 1.5 },
  TQFP: { pitch: 0.8, span: 3.0, padW: 0.4, padH: 1.5 },
  LQFP: { pitch: 0.5, span: 3.0, padW: 0.28, padH: 1.35 },
};

/** Trailing pin count in a name like `SOT-23-6`, `QFN-56`, `TSSOP-20`. */
function trailingCount(pkg: string): number | null {
  const m = /-(\d+)$/.exec(pkg);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) && n >= 2 && n <= 400 ? n : null;
}

export function landPatternFor(pkg: string): LandPattern | null {
  const raw = (pkg || "").trim().toUpperCase();
  if (!raw) return null;

  // ── chip codes: an exact match, so "0402" never matches "SOT-23-402"
  const chip = CHIP[raw];
  if (chip) {
    const f = family("passive");
    if (!f) return null;
    return { pkg, family: "Passive (two-pad)", count: 2, pads: padsFor(f, chip) };
  }

  const two = TWO_PAD[raw];
  if (two) {
    const f = family("diodes");
    if (!f) return null;
    return { pkg, family: "Two-pad", count: 2, pads: padsFor(f, two) };
  }

  // An exact hit wins before any trailing number is read: "SOT-23" names a
  // 3-pin body whose code merely ends in 23, so parsing that 23 as a pin count
  // produced a 23-pad part. Only "SOT-23-6" adds a real count on the end.
  const exactDual = DUAL[raw];
  const n = exactDual ? null : trailingCount(raw);
  const withoutCount = n === null ? raw : raw.replace(/-[0-9]+$/, "");
  const dual = exactDual ?? DUAL[withoutCount];
  if (dual) {
    const f = family(dual.tht ? "dip" : withoutCount.startsWith("SOT") || withoutCount.startsWith("TSOT") ? "sot" : "soic");
    if (!f) return null;
    // An odd count (SOT-23-5) cannot split evenly across two rows; the
    // generator puts the remainder on the first row, which is how a 5-pin SOT
    // is really laid out (3 one side, 2 the other).
    const count = n ?? dual.count;
    return {
      pkg,
      family: f.label,
      count,
      pads: padsFor(f, { count, pitch: dual.pitch, rowSpacing: dual.rowSpacing, padW: dual.padW, padH: dual.padH, drill: 0.9 }),
    };
  }

  const quad = QUAD[withoutCount] ?? QUAD[raw];
  if (quad && n && n % 4 === 0) {
    const f = family("qfp");
    if (!f) return null;
    return {
      pkg,
      family: "Quad",
      count: n,
      // span is centre-to-row, so it is half the pad run plus one pad: the
      // row sits just outside the pin field, and grows with the pin count.
      pads: padsFor(f, {
        perSide: n / 4,
        pitch: quad.pitch,
        span: Math.max(quad.span, ((n / 4 - 1) * quad.pitch) / 2 + quad.padH),
        padW: quad.padW,
        padH: quad.padH,
      }),
    };
  }

  // Module and connector packages ("SMD-53", "USB-C-16P", "TH-5P") name a
  // vendor outline, not a standard land pattern — the name alone cannot give
  // the geometry, so this says nothing rather than guessing.
  return null;
}

/** Why a package could not be resolved, phrased for the reader. */
export function unresolvedReason(pkg: string): string {
  const raw = (pkg || "").trim();
  if (!raw) return "This part carries no package name.";
  if (/^(USB|RJ|DB|TH)/i.test(raw) || /\d+P$/i.test(raw)) {
    return `${raw} is a vendor connector outline — its land pattern comes from the datasheet drawing, not from the name.`;
  }
  if (/^SMD-\d+$/i.test(raw)) {
    return `${raw} is a module outline — the number is a pad count, not a standard body, so the geometry has to come from the datasheet.`;
  }
  return `${raw} is not one of the standard families this resolves (chip codes, SOD/SMA, SOIC/SOP/SSOP/TSSOP/MSOP, SOT/TSOT, DIP, QFN/QFP).`;
}
