// IDEEZA PCB Software — static chrome markup.
// Verbatim HTML slices from the original prototype template (top bar, breadcrumb,
// toolbar). These sections are purely visual, so they are rendered via
// dangerouslySetInnerHTML for exact pixel fidelity. Brand purple -> token var.
// The notif badge and the active "select" tool state are baked in.

export const TOPBAR_HTML = `<div style="position:absolute; top:0; left:0; right:0; height:62px; background:var(--color-bg-surface); border-bottom:var(--border-width-1) solid var(--color-border-subtle); display:flex; align-items:center; padding:var(--spacing-0) var(--spacing-8); z-index:30;">
    <div class="ix-pill" style="display:flex; align-items:center; gap:var(--spacing-3); cursor:pointer; padding-right:var(--spacing-5);">
      <div style="display:flex; align-items:center; gap:var(--spacing-4);">
        <span style="display:inline-block; width:30px; height:30px; border-radius:var(--radius-full); background:var(--color-violet-600); position:relative;"><span style="position:absolute; top:8px; left:11px; width:0; height:0; border-left:10px solid var(--color-text-on-brand); border-top:7px solid transparent; border-bottom:7px solid transparent;"></span></span>
        <span style="font-weight:800; font-size:var(--font-size-2xl); letter-spacing:.5px; color:var(--color-text-primary);">IDEEZA</span>
      </div>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--color-violet-600)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"></path></svg>
    </div>
    <div style="display:flex; align-items:center; gap:var(--spacing-6); margin-left:var(--spacing-12);">
      <div class="ix-pill" style="display:flex; align-items:center; gap:var(--spacing-4); padding:var(--spacing-4) var(--spacing-8); border:var(--border-width-1-5) solid var(--color-border-default); border-radius:var(--radius-full); cursor:pointer; background:var(--color-bg-surface);">
        <span style="width:22px; height:22px; border-radius:var(--radius-full); background:radial-gradient(circle at 35% 30%, #b06be0, var(--color-violet-600)); display:flex; align-items:center; justify-content:center; color:var(--color-text-on-brand); font-size:var(--font-size-xs); font-weight:800;">i</span>
        <span style="font-weight:700; font-size:var(--font-size-md); color:var(--color-violet-600);">Earn IDZ Tokens</span>
      </div>
      <div class="ix-pill" style="display:flex; align-items:center; gap:var(--spacing-4); padding:var(--spacing-4) var(--spacing-8); border:var(--border-width-1-5) solid var(--color-border-default); border-radius:var(--radius-full); cursor:pointer; background:var(--color-bg-surface);">
        <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-primary)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="10" rx="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
        <span style="font-weight:600; font-size:var(--font-size-md); color:var(--color-text-primary);">Connect Wallet</span>
      </div>
    </div>
    <div style="margin-left:auto; display:flex; align-items:center; gap:var(--spacing-8);">
      <div class="ix-tool" style="width:34px; height:34px; border-radius:var(--radius-lg); display:flex; align-items:center; justify-content:center; cursor:pointer;"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-secondary)" stroke-width="1.8"><circle cx="12" cy="12" r="9"></circle><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.8.4-1 .9-1 1.7M12 17h.01" stroke-linecap="round"></path></svg></div>
      <div class="ix-tool" style="width:34px; height:34px; border-radius:var(--radius-lg); display:flex; align-items:center; justify-content:center; cursor:pointer;"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-secondary)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="20" r="1.4"></circle><circle cx="18" cy="20" r="1.4"></circle><path d="M2 3h3l2.3 12.3a1.5 1.5 0 0 0 1.5 1.2h8.2a1.5 1.5 0 0 0 1.5-1.2L21.5 7H6"></path></svg></div>
      <div class="ix-tool" style="position:relative; width:34px; height:34px; border-radius:var(--radius-lg); display:flex; align-items:center; justify-content:center; cursor:pointer;">
        <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-secondary)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.7 21a2 2 0 0 1-3.4 0"></path></svg>
        <span style="position:absolute; top:-2px; right:-2px; min-width:17px; height:17px; padding:var(--spacing-0) var(--spacing-2); border-radius:var(--radius-lg); background:var(--color-text-error); color:var(--color-text-on-brand); font-size:var(--font-size-2xs); font-weight:700; display:flex; align-items:center; justify-content:center;">3</span>
      </div>
      <div class="ix-pill" style="display:flex; align-items:center; gap:var(--spacing-4); cursor:pointer; padding:var(--spacing-1) var(--spacing-3) var(--spacing-1) var(--spacing-1);">
        <div style="width:34px; height:34px; border-radius:var(--radius-full); background:linear-gradient(135deg,#b06be0,var(--color-violet-600)); display:flex; align-items:center; justify-content:center; color:var(--color-text-on-brand); font-size:var(--font-size-sm); font-weight:700; flex:0 0 auto;">NR</div>
        <span style="font-weight:600; font-size:var(--font-size-md); color:var(--color-text-primary);">Nick Rough</span>
      </div>
      <div class="ix-tool" style="width:30px; height:30px; border-radius:var(--radius-lg); display:flex; align-items:center; justify-content:center; cursor:pointer;"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-tertiary)" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 6l-6 6 6 6"></path></svg></div>
    </div>
  </div>`;

export const BREADCRUMB_HTML = `<div style="position:absolute; top:62px; left:0; right:0; height:42px; background:var(--color-bg-subtle); border-bottom:var(--border-width-1) solid var(--color-border-subtle); display:flex; align-items:center; padding:var(--spacing-0) var(--spacing-10); z-index:20;">
    <div style="width:20px; height:20px; color:var(--color-violet-600); margin-right:var(--spacing-5); display:inline-flex;"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg></div>
    <span style="font-size:var(--font-size-md); color:var(--color-text-tertiary); font-weight:500;">Project Name</span>
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-disabled)" stroke-width="2" style="margin:0 8px;"><path d="M9 6l6 6-6 6"></path></svg>
    <span style="font-size:var(--font-size-md); color:var(--color-text-primary); font-weight:600;">[Product Name]</span>
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--color-violet-600)" stroke-width="2.4" style="margin-left:7px;"><path d="M6 9l6 6 6-6"></path></svg>
    <div class="ix-tool" style="width:26px; height:26px; border-radius:var(--radius-md); display:flex; align-items:center; justify-content:center; margin-left:var(--spacing-6); cursor:pointer;"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-success)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7L21 8"></path><path d="M21 3v5h-5"></path></svg></div>
  </div>`;

export const TOOLBAR_HTML = `<div style="position:absolute; top:142px; left:0; right:0; background:var(--color-bg-surface); border-bottom:var(--border-width-1) solid var(--color-border-subtle); padding:var(--spacing-3) var(--spacing-7); z-index:18; display:flex; flex-direction:column; gap:var(--spacing-3);">
    <div style="display:flex; align-items:center; gap:var(--spacing-1); flex-wrap:nowrap;">
      <!-- select cursor (active) -->
      <div class="ix-tool" style="width:30px; height:30px; border-radius:var(--radius-lg); display:flex; align-items:center; justify-content:center; cursor:pointer; background:var(--color-violet-600);">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="var(--color-text-on-brand)" stroke="var(--color-text-on-brand)" stroke-width="1.3" stroke-linejoin="round"><path d="M5 3l13 6.4-5.4 1.9L10.2 17z"></path></svg>
      </div>
      <div class="ix-tool" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;color:var(--color-text-primary);"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M9 14 4 9l5-5"></path><path d="M4 9h10.5a5.5 5.5 0 0 1 0 11H8"></path></svg></div>
      <div class="ix-tool" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;color:var(--color-text-primary);"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="m15 14 5-5-5-5"></path><path d="M20 9H9.5a5.5 5.5 0 0 0 0 11H16"></path></svg></div>
      <div class="ix-tool" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-primary)" stroke-width="1.7"><rect x="3" y="3" width="7" height="7" rx="1.5"></rect><rect x="14" y="3" width="7" height="7" rx="1.5"></rect><rect x="3" y="14" width="7" height="7" rx="1.5"></rect><rect x="14" y="14" width="7" height="7" rx="1.5"></rect></svg></div>
      <div style="width:1px; height:22px; background:var(--color-border-default); margin:var(--spacing-0) var(--spacing-2);"></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"></path><rect x="9" y="9" width="6" height="6" rx="1"></rect></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2v14a2 2 0 0 0 2 2h14"></path><path d="M2 6h14a2 2 0 0 1 2 2v14"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"></circle><path d="m20.5 20.5-3.6-3.6M11 8.5v5M8.5 11h5"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"></circle><path d="m20.5 20.5-3.6-3.6M8.5 11h5"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2.5"></rect><path d="M9 3v18M15 3v18M3 9h18M3 15h18"></path></svg></div>
      <div style="width:1px; height:22px; background:var(--color-border-default); margin:var(--spacing-0) var(--spacing-2);"></div>
      <div class="ix-tool" style="display:flex; align-items:center; gap:var(--spacing-3); padding:var(--spacing-0) var(--spacing-4); height:30px; border:var(--border-width-1) solid var(--color-border-default); border-radius:var(--radius-lg); cursor:pointer;"><span style="font-size:var(--font-size-sm); color:var(--color-text-primary); font-weight:500;">0.05</span><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-tertiary)" stroke-width="2.2"><path d="M6 9l6 6 6-6"></path></svg></div>
      <div class="ix-tool" style="display:flex; align-items:center; gap:var(--spacing-3); padding:var(--spacing-0) var(--spacing-4); height:30px; border:var(--border-width-1) solid var(--color-border-default); border-radius:var(--radius-lg); cursor:pointer;"><span style="font-size:var(--font-size-sm); color:var(--color-text-primary); font-weight:500;">Inch</span><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-tertiary)" stroke-width="2.2"><path d="M6 9l6 6 6-6"></path></svg></div>
      <div style="width:1px; height:22px; background:var(--color-border-default); margin:var(--spacing-0) var(--spacing-2);"></div>
      <div class="ix-tool" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;color:var(--color-text-primary);"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="6" y="6" width="12" height="12" rx="1.6"></rect><path d="M9 6V3M15 6V3M9 21v-3M15 21v-3M6 9H3M6 15H3M21 9h-3M21 15h-3" stroke-linecap="round"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M5 18V9a2 2 0 0 1 2-2h12"></path><circle cx="5" cy="18" r="1.7" fill="currentColor" stroke="none"></circle><circle cx="19" cy="7" r="1.7" fill="currentColor" stroke="none"></circle></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"><path d="M4 7h16M4 12h16M4 17h16"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h6"></path><path d="M9 7h10a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H9l-3.2-5z"></path></svg></div>
      <div style="width:1px; height:22px; background:var(--color-border-default); margin:var(--spacing-0) var(--spacing-2);"></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v9M6.5 12h11M9 16h6M11 19.5h2"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v8"></path><path d="M7 11h10l-5 8z"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21V8M7.5 12.5 12 8l4.5 4.5M8 4.5h8"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8h7v8H4z"></path><path d="M11 12h6M15 9l3 3-3 3"></path></svg></div>
      <div style="width:1px; height:22px; background:var(--color-border-default); margin:var(--spacing-0) var(--spacing-2);"></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 3v18M20 3v18"></path><rect x="9" y="8" width="6" height="8" rx="1"></rect></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 4h18M3 20h18"></path><rect x="8" y="9" width="8" height="6" rx="1"></rect></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18"></path><path d="M8 6 4 12l4 6z" fill="currentColor" stroke="none"></path><path d="M16 6 20 12l-4 6z"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h18"></path><path d="M6 8 12 4l6 4z" fill="currentColor" stroke="none"></path><path d="M6 16 12 20l6-4z"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M9 4a8 8 0 1 1-6 2.7"></path><path d="M3 3v4h4"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M15 4a8 8 0 1 0 6 2.7"></path><path d="M21 3v4h-4"></path></svg></div>
      <div style="width:1px; height:22px; background:var(--color-border-default); margin:var(--spacing-0) var(--spacing-2);"></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="9" y="9" width="11" height="11" rx="2.5" fill="var(--color-text-on-brand)"></rect><rect x="4" y="4" width="11" height="11" rx="2.5" fill="currentColor" stroke="none"></rect></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="4" y="4" width="11" height="11" rx="2.5" fill="var(--color-text-on-brand)"></rect><rect x="9" y="9" width="11" height="11" rx="2.5" fill="currentColor" stroke="none"></rect></svg></div>
    </div>
    <div style="display:flex; align-items:center; gap:var(--spacing-1);">
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M6 21V4h11l-2.5 3.5L17 11H6"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M7 20V5h8l-2 3.5L15 12H7"></path><circle cx="7" cy="20" r="1.4" fill="currentColor" stroke="none"></circle></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21s7-6.5 7-12a7 7 0 1 0-14 0c0 5.5 7 12 7 12z"></path><circle cx="12" cy="9" r="2.3"></circle></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M5 6h8M5 12h11M5 18h5"></path><circle cx="16" cy="6" r="2.3"></circle><circle cx="19" cy="12" r="2.3"></circle><circle cx="13" cy="18" r="2.3"></circle></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8h11l-3-3M20 16H9l3 3"></path></svg></div>
      <div class="ix-tool ix-ico" style="width:30px;height:30px;border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M12 2.5v3M12 18.5v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M2.5 12h3M18.5 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"></path></svg></div>
    </div>
  </div>`;

export const COVER_HTML = `<div data-screen-label="Cover" style="position: absolute; inset: 0; z-index: 90; background: var(--color-bg-inverse); overflow: hidden;">
    <!-- top-right purple arrow -->
    <svg width="170" height="170" viewBox="0 0 170 170" style="position:absolute; top:60px; right:120px;"><path d="M150 20 L40 130 M40 130 L40 78 M40 130 L92 130" fill="none" stroke="var(--color-violet-600)" stroke-width="9" stroke-linecap="square"></path></svg>
    <!-- scribble -->
    <svg width="360" height="220" viewBox="0 0 360 220" style="position:absolute; bottom:120px; right:40px; opacity:.9;"><path d="M20 110 C20 40 90 40 90 110 C90 180 160 180 160 110 C160 40 230 40 230 110 C230 180 300 180 300 110 C300 40 350 60 350 130" fill="none" stroke="var(--color-text-on-brand)" stroke-width="2.5"></path></svg>
    <!-- four point star -->
    <svg width="120" height="120" viewBox="0 0 120 120" style="position:absolute; bottom:230px; right:330px;"><path d="M60 8 C64 40 80 56 112 60 C80 64 64 80 60 112 C56 80 40 64 8 60 C40 56 56 40 60 8Z" fill="none" stroke="var(--color-text-on-brand)" stroke-width="2.5"></path></svg>
    <!-- sunburst bottom-left -->
    <svg width="260" height="180" viewBox="0 0 260 180" style="position:absolute; bottom:-20px; left:-30px;"><g stroke="var(--color-text-on-brand)" stroke-width="9" stroke-linecap="round">
      <line x1="40" y1="170" x2="40" y2="70"></line><line x1="40" y1="170" x2="14" y2="86"></line><line x1="40" y1="170" x2="72" y2="84"></line>
      <line x1="40" y1="170" x2="104" y2="108"></line><line x1="40" y1="170" x2="120" y2="150"></line><line x1="40" y1="170" x2="6" y2="120"></line>
    </g></svg>
    <div style="position:absolute; top:300px; left:170px;">
      <div style="font-family:var(--font-family-body); font-weight:200; font-size:170px; line-height:.92; letter-spacing:-4px; color:var(--color-text-on-brand);">PCB</div>
      <div style="font-family:var(--font-family-body); font-weight:200; font-size:170px; line-height:.92; letter-spacing:-4px; color:var(--color-text-on-brand);">Software</div>
    </div>
    <div style="position:absolute; top:498px; right:430px; font-weight:300; font-size:30px; color:var(--color-bg-brand-subtle);">Product Design Team</div>
    <div data-act="enter" class="ix-cover-enter" style="position:absolute; bottom:70px; left:170px; display:flex; align-items:center; gap:var(--spacing-6); padding:var(--spacing-8) var(--spacing-16); background:var(--color-violet-600); color:var(--color-text-on-brand); border-radius:var(--radius-full); font-weight:600; font-size:var(--font-size-lg); cursor:pointer;">
      <span>Launch the editor</span>
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-on-brand)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"></path></svg>
    </div>
    <div style="position:absolute; top:42px; left:170px; display:flex; align-items:center; gap:var(--spacing-5); color:var(--color-text-on-brand); font-weight:700; letter-spacing:1px; font-size:var(--font-size-md);">
      <span style="display:inline-block; width:26px; height:26px; border-radius:var(--radius-full); background:var(--color-violet-600); position:relative;"><span style="position:absolute; top:7px; left:9px; width:0; height:0; border-left:9px solid var(--color-text-on-brand); border-top:6px solid transparent; border-bottom:6px solid transparent;"></span></span>
      IDEEZA
    </div>
  </div>`;

export const AXIS_SVG = `<svg width="26" height="26" viewBox="0 0 32 32" fill="none" stroke="var(--color-text-tertiary)" stroke-width="1.5" stroke-linecap="round"><path d="M16 16V6M16 16l8.5 5M16 16L7.5 21"></path><circle cx="16" cy="6" r="2"></circle><circle cx="24.5" cy="21" r="2"></circle><circle cx="7.5" cy="21" r="2"></circle></svg>`;
export const FLOAT_SVGS = [`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21V8M7.5 12.5 12 8l4.5 4.5M8 4.5h8"></path></svg>`, `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v9M6.5 12h11M9 16h6M11 19.5h2"></path></svg>`, `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v8"></path><path d="M7 11h10l-5 8z"></path></svg>`, `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M6 21V4h11l-2.5 3.5L17 11H6"></path></svg>`, `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8h7v8H4z"></path><path d="M11 12h6M15 9l3 3-3 3"></path></svg>`];
export const PLANE_SVG = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fe2ad4" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7l9-4 9 4-9 4-9-4z"></path><path d="M3 7v6l9 4 9-4V7"></path></svg>`;
export const NEXT_SVG = `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-on-brand)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"></path></svg>`;
