// POST /api/kicad
//
// Runs KiCad's headless CLI against a board file generated by the editor
// (see src/lib/pcb/kicad-export.ts). This is what turns the PCB step into a
// real manufacturing pipeline: actual Gerbers / DRC from the actual design.
//
// Request:  { job: "gerber" | "drc", board: string /* .kicad_pcb text */ }
// Response: gerber → application/zip download; drc → JSON report.
//           501 with an install hint when kicad-cli isn't on this server.
//
// kicad-cli discovery: $KICAD_CLI, PATH, then the macOS app-bundle location.

import { NextResponse } from "next/server";
import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

export const runtime = "nodejs";

const execFileP = promisify(execFile);

const MAX_BOARD_BYTES = 5_000_000;

function findKicadCli(): string | null {
  const candidates = [
    process.env.KICAD_CLI,
    "kicad-cli",
    "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli",
    "/usr/lib/kicad/bin/kicad-cli",
    "/usr/bin/kicad-cli",
  ].filter(Boolean) as string[];
  for (const c of candidates) {
    if (c === "kicad-cli") return c; // resolved via PATH at exec time
    if (existsSync(c)) return c;
  }
  return null;
}

async function hasCli(cli: string): Promise<boolean> {
  try {
    await execFileP(cli, ["version"], { timeout: 10_000 });
    return true;
  } catch {
    return false;
  }
}

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const { job, board, layers, drill, name } =
    typeof body === "object" && body !== null
      ? (body as { job?: unknown; board?: unknown; layers?: unknown; drill?: unknown; name?: unknown })
      : {};
  if ((job !== "gerber" && job !== "drc") || typeof board !== "string") {
    return NextResponse.json(
      { error: "Expected { job: 'gerber' | 'drc', board: string }" },
      { status: 400 },
    );
  }
  if (board.length > MAX_BOARD_BYTES || !board.trimStart().startsWith("(kicad_pcb")) {
    return NextResponse.json({ error: "Not a .kicad_pcb document" }, { status: 400 });
  }

  const cli = findKicadCli();
  if (!cli || !(await hasCli(cli))) {
    return NextResponse.json(
      {
        error:
          "KiCad is not installed on this server. Install KiCad 8+ (brew install --cask kicad, " +
          "or run the app in a Docker image with kicad-cli) or set KICAD_CLI to the binary path.",
      },
      { status: 501 },
    );
  }

  // UIUX-100 — the caller picks which layers get plotted; the board file's own
  // name becomes the Gerber file prefix, so the dialog's name field is real.
  const plot = Array.isArray(layers)
    ? layers.filter((l): l is string => typeof l === "string" && /^[A-Za-z0-9.]{2,12}$/.test(l))
    : [];
  const wantDrill = drill !== false;
  const base = typeof name === "string" && /^[A-Za-z0-9._-]{1,48}$/.test(name) ? name : "board";

  const work = await fs.mkdtemp(path.join(os.tmpdir(), "ideeza-kicad-"));
  const boardPath = path.join(work, `${base}.kicad_pcb`);
  try {
    await fs.writeFile(boardPath, board, "utf8");

    if (job === "drc") {
      const reportPath = path.join(work, "drc.json");
      // DRC exits non-zero when violations exist — that's still a report.
      await execFileP(
        cli,
        ["pcb", "drc", "--format", "json", "--output", reportPath, boardPath],
        { timeout: 120_000 },
      ).catch(() => {});
      const report = await fs.readFile(reportPath, "utf8");
      return new NextResponse(report, {
        headers: { "Content-Type": "application/json" },
      });
    }

    // job === "gerber": plot gerbers + drill files, zip the folder.
    const outDir = path.join(work, "gerbers");
    await fs.mkdir(outDir);
    if (plot.length) {
      await execFileP(
        cli,
        ["pcb", "export", "gerbers", "--layers", plot.join(","), "--output", outDir + "/", boardPath],
        { timeout: 120_000 },
      );
    }
    if (wantDrill) {
      await execFileP(cli, ["pcb", "export", "drill", "--output", outDir + "/", boardPath], {
        timeout: 120_000,
      });
    }
    const zipPath = path.join(work, "gerbers.zip");
    await execFileP("zip", ["-r", "-j", zipPath, outDir], { timeout: 60_000 });
    const zip = await fs.readFile(zipPath);
    return new NextResponse(new Uint8Array(zip), {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${base}-gerbers.zip"`,
      },
    });
  } catch (e) {
    return NextResponse.json(
      { error: `kicad-cli failed: ${e instanceof Error ? e.message : String(e)}` },
      { status: 500 },
    );
  } finally {
    fs.rm(work, { recursive: true, force: true }).catch(() => {});
  }
}
